baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://matthieupetite.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: "experience"

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

collections:
  experiences:
    output: true
    permalink: /:collection/:name
  certifications:
    output: false
  competences:
    output: false